# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

variables:
  - name: token
    value: 23123123

pool:
  name: Default 

steps:
- script: echo "##vso[task.setvariable token=one]secondValue"
  displayName: 'testing variable'


