# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

stages:
  - stage: Read_WI
    jobs:
      - job: readingWI
        pool:
          name: Default
        
        steps:
          - script: curl --version
            displayName: 'version'

          - script: curl --url https://mo-cd1351cf9.coe-alm.c.eu-de-1.cloud.sap:50001/sap/opu/odata/SALM/EXT_DEVOPS_INTEG_SRV/WorkItemSet(guid=guid'$(WID)')?$expand=toWIActualRelease,toWIAttachment,toWIText,toWICategory -H "Authorization:Basic STg0MTM5ODpvdHNlbnJlMjI=" -H "Accept:application/json"
            displayName: 'Reading my WI'

###### POSTING TEXT #################

  - stage: Posting_Text
    jobs:
      - job: postNewText
        pool:
          name: Default
        
        steps:
          - script: curl --request GET -v --url https://mo-cd1351cf9.coe-alm.c.eu-de-1.cloud.sap:50001/sap/opu/odata/SALM/EXT_DEVOPS_INTEG_SRV/WorkItemSet(guid=guid'FA163E5E-4B54-1EDC-BBB0-8DFCC4252095')/toWIText -H "Authorization:Basic STg0MTM5ODpvdHNlbnJlMjI=" -H "Accept:application/json" -H "x-csrf-token:fetch"
            displayName: 'Getting CSRF token'
                
          - script: curl -v --request POST --url https://mo-cd1351cf9.coe-alm.c.eu-de-1.cloud.sap:50001/sap/opu/odata/SALM/EXT_DEVOPS_INTEG_SRV/WorkItemSet(guid=guid'FA163E5E-4B54-1EDC-BBB0-8DFCC4252095')/toWIText -H "Authorization:Basic STg0MTM5ODpvdHNlbnJlMjI=" -H "Accept:application/json" -H "x-csrf-token:GUuWZCOwyRRBfmyIHjXAIg=="
            displayName: 'Posting Text'


          - task: InvokeRESTAPI@1
            inputs:
              connectionType: 'connectedServiceNameARM'
              method: 'GET'
              headers: |
                {
                  "Content-Type":"application/json"
                }
              body: |
                {
                  "textType": "S105",
                  "textContent": "New Comment Text"
                }
              urlSuffix: https://mo-cd1351cf9.coe-alm.c.eu-de-1.cloud.sap:50001/sap/opu/odata/SALM/EXT_DEVOPS_INTEG_SRV/WorkItemSet(guid=guid'FA163E5E-4B54-1EDC-BBB0-8DFCC4252095')
              waitForCompletion: 'false'
